name: Bug report
description: Report a reproducible bug in Theo OpenVoice
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please provide enough detail for us to reproduce it.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what you expected to happen.
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instructions.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS:
        - Python version:
        - Theo version:
        - Model/engine:
        - Install method:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and errors
      description: Paste relevant logs or error messages.
      render: shell
    validations:
      required: false
